# Promise Tracker Pipeline Job Definitions
# 
# MINIMAL CONFIGURATION: Only job classes and triggers
# All scheduling, timeouts, retries configured in Google Cloud Scheduler
#
# Each Cloud Scheduler job should target:
# POST https://your-cloud-run-service/jobs/{stage}/{job_name}

stages:
  ingestion:
    jobs:
      canada_news:
        class: "pipeline.stages.ingestion.canada_news.CanadaNewsIngestion"
        triggers:
          - stage: "processing"
            job: "news_processor"
            condition: "successful_run"
        
      legisinfo_bills:
        class: "pipeline.stages.ingestion.legisinfo_bills.LegisInfoBillsIngestion"
        triggers:
          - stage: "processing"
            job: "bill_processor"
            condition: "successful_run"
        
      orders_in_council:
        class: "pipeline.stages.ingestion.orders_in_council.OrdersInCouncilIngestion"
        triggers:
          - stage: "processing"
            job: "oic_processor"
            condition: "successful_run"
        
      canada_gazette:
        class: "pipeline.stages.ingestion.canada_gazette.CanadaGazetteIngestion"
        triggers:
          - stage: "processing"
            job: "gazette_processor"
            condition: "successful_run"

  processing:
    jobs:
      news_processor:
        class: "pipeline.stages.processing.canada_news_processor.CanadaNewsProcessor"
        triggers:
          - stage: "linking"
            job: "evidence_linker"
            condition: "successful_run"
        
      bill_processor:
        class: "pipeline.stages.processing.legisinfo_processor.LegisInfoProcessor"
        triggers:
          - stage: "linking"
            job: "evidence_linker"
            condition: "successful_run"
        
      oic_processor:
        class: "pipeline.stages.processing.orders_in_council_processor.OrdersInCouncilProcessor"
        triggers:
          - stage: "linking"
            job: "evidence_linker"
            condition: "successful_run"
        
      gazette_processor:
        class: "pipeline.stages.processing.canada_gazette_processor.CanadaGazetteProcessor"
        triggers:
          - stage: "linking"
            job: "evidence_linker"
            condition: "successful_run"

  linking:
    jobs:
      evidence_linker:
        class: "pipeline.stages.linking.evidence_linker.EvidenceLinker"
        triggers:
          - stage: "linking"
            job: "progress_scorer"
            condition: "evidence_updated"
        
      progress_scorer:
        class: "pipeline.stages.linking.progress_scorer.ProgressScorer"

  maintenance:
    jobs:
      promise_enricher:
        class: "pipeline.stages.linking.promise_enricher.PromiseEnricher"

# Global settings (only what's not handled by Cloud Scheduler)
global:
  max_concurrent_jobs: 3  # For batch execution
  error_notification_webhook: "${ERROR_WEBHOOK_URL}" 