name: Scrape GDP Data

on:
  workflow_dispatch:
  schedule:
    # Daily at 6:23 AM UTC
    - cron: "23 6 * * *"
  # For hourly at 42 minutes past the hour: '42 * * * *'

permissions:
  contents: write

env:
  STATS_CAN_URL: https://www150.statcan.gc.ca/t1/tbl1/en/dtl!downloadDbLoadingData-nonTraduit.action?pid=3610010401&latestN=0&startDate=19610101&endDate=&csvLocale=en&selectedMembers=%5B%5B1%5D%2C%5B1%5D%2C%5B1%5D%2C%5B%5D%5D&checkedLevels=3D1%2C3D2%2C3D3%2C3D4
  COMMIT_MSG: Update GDP Data

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
      - uses: actions/checkout@v4
      - name: Run the scraper
        run: |
          python scrape.py '${{ env.STATS_CAN_URL }}' metrics/statscan/gdp.json Estimates
      # Commit as brendan so vercel will deploy it
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "brendan@brendansamek.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "${{ env.COMMIT_MSG }} - ${timestamp}" || exit 0
          git pull --rebase
          git push
