name: Scrape Primary Energy Production Data

on:
  push:
  workflow_dispatch:
  schedule:
    # Daily at 10:23 AM UTC
    - cron: "23 10 * * *"
  # For hourly at 42 minutes past the hour: '42 * * * *'

permissions:
  contents: write

env:
  STATS_CAN_URL: https://www150.statcan.gc.ca/t1/tbl1/en/dtl!downloadDbLoadingData-nonTraduit.action?pid=2510007901&latestN=5&startDate=&endDate=&csvLocale=en&selectedMembers=%5B%5B%5D%2C%5B%5D%2C%5B%5D%5D&checkedLevels=0D1%2C1D1%2C1D2%2C1D3%2C2D1
  COMMIT_MSG: Update Primary Energy Production Data

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
      - uses: actions/checkout@v4
      - name: Run the scraper
        run: |
          python scrape.py '${{ env.STATS_CAN_URL }}' metrics/statscan/primary-energy.json "Supply and demand characteristics"
      # Commit as brendan so vercel will deploy it
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "brendan@brendansamek.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "${{ env.COMMIT_MSG }} - ${timestamp}" || exit 0
          git pull --rebase
          git push